spring:
  datasource:
    url: jdbc:postgresql://ep-flat-credit-a11ev4zn-pooler.ap-southeast-1.aws.neon.tech/neondb?&sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_2uU4NBlzLivE
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080
